-intstyle "ise" -incremental -o "C:/Users/sratt/Desktop/xillinx prog/Not_GATE/Not_Gate_mod_isim_beh.exe" -prj "C:/Users/sratt/Desktop/xillinx prog/Not_GATE/Not_Gate_mod_beh.prj" "work.Not_Gate_mod" 
